--- # apt install ansible -y
-
  name: "Infrastructure Setup for security-team-server"
  hosts: localhost
  become: yes
  tasks:
    - name: "Add team accounts as sudo users"
      user:
        name: '{{ item }}'
        create_home: yes
        shell: /bin/bash
        append: yes
        groups: 'sudo'
        state: present
      loop:
        - andres
        - daniel
        - jordani
        - paul
        - massa

...
